### ISSUE TITLE
public config.py

### ISSUE THREAD

**Issue by cypherain** [Spandan2022/ML_Stock_Trading_Script#1]
Your config.py with api key is public to everyone...

**Comment by Spandan2022** [comment]
Thank you for pointing that out, the API key in config.py is a dummy api key, therefore there are no worries. I will update the config.py file with a comment that indicates that the API key is a dummy. Thanks,Spandan DasOn Jan 31, 2024, at 3:16 AM, 3n50 ***@***.***> wrote:﻿
Your config.py with api key is public to everyone...
